#
# (C) Copyright 2014 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CHROMEOS) += cmd/
obj-$(CONFIG_CHROMEOS) += lib/
obj-$(CONFIG_CHROMEOS) += vboot/
obj-$(CONFIG_CHROMEOS) += $(SOC)/
