#
# (C) Copyright 2014 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CHROMEOS_TEST)	+= cmd_cros_tpm_test.o
obj-$(CONFIG_CHROMEOS_TEST)	+= cmd_cros_test.o
obj-$(CONFIG_CHROMEOS_TEST)	+= cmd_vbexport_test.o
obj-$(CONFIG_CHROMEOS_TEST)	+= cmd_vboot_test.o
obj-$(CONFIG_CROS_LEGACY_VBOOT)	+= cmd_vboot_twostop.o
obj-$(CONFIG_CHROMEOS)	+= cmd_vboot.o
